# Generated by Django 4.1 on 2022-08-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me04', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['register']},
        ),
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Profil fotografı'),
        ),
    ]
