# Generated by Django 4.1 on 2022-08-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me04', '0002_alter_team_options_alter_team_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='YAŞ'),
        ),
    ]
